#ifndef __ESP_GALLERY_CONFIGS_H__
#define __ESP_GALLERY_CONFIGS_H__

#define GRID_ELEMENT_HEIGHT 80
#define GRID_ELEMENT_WIDTH 80

#define MAX_IMAGE_WIDTH 240
#define MAX_IMAGE_HEIGHT 320

#define THUMBNAIL_WIDTH_SCALE_FACTOR 3
#define THUMBNAIL_HEIGHT_SCALE_FACTOR 3

#define GRID_MAX_ROWS (MAX_IMAGE_HEIGHT/GRID_ELEMENT_HEIGHT)
#define GRID_MAX_COLS (MAX_IMAGE_WIDTH/GRID_ELEMENT_WIDTH)

#define HIGHLIGHT_COLOR 0x001F
#define HIGHLIGHT_THICKNESS 2

#define BG_COLOR 0x0000

#define SPLACH_IMAGE_PATH "/esp_gallery_data/splash.png"
#define SPLASH_MIN_DISPLAY_TIME_MS 500

#endif
